/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class ManutencaoMaquinaView extends javax.swing.JFrame {

    /**
     * Creates new form ManutencaoMaquinaView
     */
    public ManutencaoMaquinaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDMaquinasManutencao = new javax.swing.JTextField();
        txtIDManutencaoMaquinas = new javax.swing.JTextField();
        txtTipoDProblema = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoDProblema = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoSolucaoProblema = new javax.swing.JTextArea();
        txtDataManutencao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCriarManutencaoMaquinas = new javax.swing.JButton();
        btnLerManutencaoMaquinas = new javax.swing.JButton();
        btnAtualizarManutencaoMaquinas = new javax.swing.JButton();
        btnExcluirManutencaoMaquinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID MANUTENÇÃO");

        jLabel2.setText("ID MAQUINA");

        txtIDMaquinasManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMaquinasManutencaoActionPerformed(evt);
            }
        });

        txtIDManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDManutencaoMaquinasActionPerformed(evt);
            }
        });

        txtTipoDProblema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Problema", "Rede wifi sem conectar", "Computador desliga-se repentinamente", "Problemas de arranque", "Computador super lento", "Entrada USB não funciona", "Computador sem som", "Microfone não funciona", "Aquece demasiado e faz barulho", "Problemas para processar alguns programas", "Tela Azul" }));
        txtTipoDProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoDProblemaActionPerformed(evt);
            }
        });

        jLabel3.setText("TIPO DE PROBLEMA");

        jLabel4.setText("DESCRIÇÃO DO PROBLEMA");

        jLabel5.setText("DESCRIÇÃO DA SOLUÇÃO DO PROBLEMA");

        txtDescricaoDProblema.setColumns(20);
        txtDescricaoDProblema.setRows(5);
        txtDescricaoDProblema.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtDescricaoDProblemaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtDescricaoDProblema);

        txtDescricaoSolucaoProblema.setColumns(20);
        txtDescricaoSolucaoProblema.setRows(5);
        txtDescricaoSolucaoProblema.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtDescricaoSolucaoProblemaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(txtDescricaoSolucaoProblema);

        txtDataManutencao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataManutencaoActionPerformed(evt);
            }
        });

        jLabel6.setText("DATA DA MANUTENÇÃO");

        btnCriarManutencaoMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aba.png"))); // NOI18N
        btnCriarManutencaoMaquinas.setText("CRIAR");
        btnCriarManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarManutencaoMaquinasActionPerformed(evt);
            }
        });

        btnLerManutencaoMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/livro.png"))); // NOI18N
        btnLerManutencaoMaquinas.setText("LER");
        btnLerManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerManutencaoMaquinasActionPerformed(evt);
            }
        });

        btnAtualizarManutencaoMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atualizada.png"))); // NOI18N
        btnAtualizarManutencaoMaquinas.setText("ATUALIZAR");
        btnAtualizarManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarManutencaoMaquinasActionPerformed(evt);
            }
        });

        btnExcluirManutencaoMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excluir.png"))); // NOI18N
        btnExcluirManutencaoMaquinas.setText("EXCLUIR");
        btnExcluirManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirManutencaoMaquinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDMaquinasManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoDProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDataManutencao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnCriarManutencaoMaquinas)
                .addGap(74, 74, 74)
                .addComponent(btnLerManutencaoMaquinas)
                .addGap(61, 61, 61)
                .addComponent(btnAtualizarManutencaoMaquinas)
                .addGap(79, 79, 79)
                .addComponent(btnExcluirManutencaoMaquinas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(txtIDManutencaoMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(600, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addComponent(txtTipoDProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDMaquinasManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarManutencaoMaquinas)
                    .addComponent(btnLerManutencaoMaquinas)
                    .addComponent(btnAtualizarManutencaoMaquinas)
                    .addComponent(btnExcluirManutencaoMaquinas))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(txtIDManutencaoMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDManutencaoMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDManutencaoMaquinasActionPerformed

    private void txtIDMaquinasManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMaquinasManutencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMaquinasManutencaoActionPerformed

    private void txtTipoDProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoDProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoDProblemaActionPerformed

    private void txtDescricaoDProblemaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtDescricaoDProblemaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoDProblemaAncestorAdded

    private void txtDescricaoSolucaoProblemaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtDescricaoSolucaoProblemaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoSolucaoProblemaAncestorAdded

    private void txtDataManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataManutencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataManutencaoActionPerformed

    private void btnCriarManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarManutencaoMaquinasActionPerformed
    String idMaquina = txtIDMaquinasManutencao.getText();
    String idManutencao = txtIDManutencaoMaquinas.getText();
    String tipoProblema = (String) txtTipoDProblema.getSelectedItem();
    String descricaoProblema = txtDescricaoDProblema.getText();
    String descricaoSolucao = txtDescricaoSolucaoProblema.getText();
    String dataManutencao = txtDataManutencao.getText();

    
    JOptionPane.showMessageDialog(this, "Manutenção criada com sucesso!\n" +
        "ID Manutenção: " + idManutencao +
        "\nID Máquina: " + idMaquina +
        "\nTipo de Problema: " + tipoProblema +
        "\nData da Manutenção: " + dataManutencao);
    
    limparCampos();
    }//GEN-LAST:event_btnCriarManutencaoMaquinasActionPerformed

    private void btnLerManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerManutencaoMaquinasActionPerformed
        String idMaquina = txtIDMaquinasManutencao.getText();
    String idManutencao = txtIDManutencaoMaquinas.getText();
    String tipoProblema = (String) txtTipoDProblema.getSelectedItem();
    String descricaoProblema = txtDescricaoDProblema.getText();
    String descricaoSolucao = txtDescricaoSolucaoProblema.getText();
    String dataManutencao = txtDataManutencao.getText();

    
    JOptionPane.showMessageDialog(this, "Exibindo os dados da manutenção...\n" +
        "ID Manutenção: " + idManutencao +
        "\nID Máquina: " + idMaquina +
        "\nTipo de Problema: " + tipoProblema +
        "\nData da Manutenção: " + dataManutencao);
        
        
        
       
        
        limparCampos();
    }//GEN-LAST:event_btnLerManutencaoMaquinasActionPerformed

    private void btnAtualizarManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarManutencaoMaquinasActionPerformed
       String idMaquina = txtIDMaquinasManutencao.getText();
    String idManutencao = txtIDManutencaoMaquinas.getText();
    String tipoProblema = (String) txtTipoDProblema.getSelectedItem();
    String descricaoProblema = txtDescricaoDProblema.getText();
    String descricaoSolucao = txtDescricaoSolucaoProblema.getText();
    String dataManutencao = txtDataManutencao.getText();

    
    JOptionPane.showMessageDialog(this, "Manutenção atualizada com sucesso!\n" +
        "ID Manutenção: " + idManutencao +
        "\nID Máquina: " + idMaquina +
        "\nTipo de Problema: " + tipoProblema +
        "\nData da Manutenção: " + dataManutencao);
        
        
        limparCampos();
    }//GEN-LAST:event_btnAtualizarManutencaoMaquinasActionPerformed

    private void btnExcluirManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirManutencaoMaquinasActionPerformed
        
        String idMaquina = txtIDMaquinasManutencao.getText();
    String idManutencao = txtIDManutencaoMaquinas.getText();
    String tipoProblema = (String) txtTipoDProblema.getSelectedItem();
    String descricaoProblema = txtDescricaoDProblema.getText();
    String descricaoSolucao = txtDescricaoSolucaoProblema.getText();
    String dataManutencao = txtDataManutencao.getText();

    
    JOptionPane.showMessageDialog(this, "Manutenção excluída com sucesso!\n" +
        "ID Manutenção: " + idManutencao +
        "\nID Máquina: " + idMaquina +
        "\nTipo de Problema: " + tipoProblema +
        "\nData da Manutenção: " + dataManutencao);
        
        
        limparCampos();
    }//GEN-LAST:event_btnExcluirManutencaoMaquinasActionPerformed

    private void limparCampos(){
    txtDataManutencao.setText("");
    txtDescricaoDProblema.setText("");
    txtDescricaoSolucaoProblema.setText("");
    txtIDManutencaoMaquinas.setText("");
    txtIDMaquinasManutencao.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMaquinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMaquinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMaquinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMaquinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManutencaoMaquinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarManutencaoMaquinas;
    private javax.swing.JButton btnCriarManutencaoMaquinas;
    private javax.swing.JButton btnExcluirManutencaoMaquinas;
    private javax.swing.JButton btnLerManutencaoMaquinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField txtDataManutencao;
    private javax.swing.JTextArea txtDescricaoDProblema;
    private javax.swing.JTextArea txtDescricaoSolucaoProblema;
    private javax.swing.JTextField txtIDManutencaoMaquinas;
    private javax.swing.JTextField txtIDMaquinasManutencao;
    private javax.swing.JComboBox<String> txtTipoDProblema;
    // End of variables declaration//GEN-END:variables
}
