/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Joel
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMaquinas = new javax.swing.JMenu();
        SubMenuMaquinasManutencao = new javax.swing.JMenuItem();
        SubMenuMaquinasCadastro = new javax.swing.JMenuItem();
        MenuLaboratorio = new javax.swing.JMenu();
        SubMenuLaboratorioMaquinas = new javax.swing.JMenuItem();
        SubMenuLaboratorioPecas = new javax.swing.JMenuItem();
        MenuPecas = new javax.swing.JMenu();
        SubMenuPecasCadastro = new javax.swing.JMenuItem();
        SubMenuPecasManutencao = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        SubMenuRelatorioMaquinas = new javax.swing.JMenuItem();
        SubMenuRelatorioPecas = new javax.swing.JMenuItem();
        SubMenuRelatorioLaboratorio = new javax.swing.JMenuItem();
        MenuManutencao = new javax.swing.JMenu();
        SubMenuManutencaoPecas = new javax.swing.JMenuItem();
        SubMenuManutencaoMaquinas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenuMaquinas.setText("Maquinas");

        SubMenuMaquinasManutencao.setText("Manutenção de Maquinas");
        SubMenuMaquinasManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuMaquinasManutencaoActionPerformed(evt);
            }
        });
        MenuMaquinas.add(SubMenuMaquinasManutencao);

        SubMenuMaquinasCadastro.setText("Cadastro De Maquinas");
        SubMenuMaquinasCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuMaquinasCadastroActionPerformed(evt);
            }
        });
        MenuMaquinas.add(SubMenuMaquinasCadastro);

        jMenuBar1.add(MenuMaquinas);

        MenuLaboratorio.setText("Laboratorio");

        SubMenuLaboratorioMaquinas.setText("Maquinas");
        SubMenuLaboratorioMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuLaboratorioMaquinasActionPerformed(evt);
            }
        });
        MenuLaboratorio.add(SubMenuLaboratorioMaquinas);

        SubMenuLaboratorioPecas.setText("Pecas");
        SubMenuLaboratorioPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuLaboratorioPecasActionPerformed(evt);
            }
        });
        MenuLaboratorio.add(SubMenuLaboratorioPecas);

        jMenuBar1.add(MenuLaboratorio);

        MenuPecas.setText("Pecas");

        SubMenuPecasCadastro.setText("Cadastro De Peças");
        SubMenuPecasCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuPecasCadastroActionPerformed(evt);
            }
        });
        MenuPecas.add(SubMenuPecasCadastro);

        SubMenuPecasManutencao.setText("Manutenção De Peças");
        SubMenuPecasManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuPecasManutencaoActionPerformed(evt);
            }
        });
        MenuPecas.add(SubMenuPecasManutencao);

        jMenuBar1.add(MenuPecas);

        MenuRelatorios.setText("Relatorios");

        SubMenuRelatorioMaquinas.setText("Relatorio de Maquinas");
        SubMenuRelatorioMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuRelatorioMaquinasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(SubMenuRelatorioMaquinas);

        SubMenuRelatorioPecas.setText("Relatorio de Pecas");
        SubMenuRelatorioPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuRelatorioPecasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(SubMenuRelatorioPecas);

        SubMenuRelatorioLaboratorio.setText("Relatorio de Laboratorio");
        SubMenuRelatorioLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuRelatorioLaboratorioActionPerformed(evt);
            }
        });
        MenuRelatorios.add(SubMenuRelatorioLaboratorio);

        jMenuBar1.add(MenuRelatorios);

        MenuManutencao.setText("Manutencao");

        SubMenuManutencaoPecas.setText("Manutencao de pecas");
        SubMenuManutencaoPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuManutencaoPecasActionPerformed(evt);
            }
        });
        MenuManutencao.add(SubMenuManutencaoPecas);

        SubMenuManutencaoMaquinas.setText("Manutencao de Maquinas");
        SubMenuManutencaoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuManutencaoMaquinasActionPerformed(evt);
            }
        });
        MenuManutencao.add(SubMenuManutencaoMaquinas);

        jMenuBar1.add(MenuManutencao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuMaquinasManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuMaquinasManutencaoActionPerformed
        ManutencaoMaquinaView manutencaoMaquinaView = new ManutencaoMaquinaView();
        manutencaoMaquinaView.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuMaquinasManutencaoActionPerformed

    private void SubMenuMaquinasCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuMaquinasCadastroActionPerformed
        CadastroMaquinasView cadastroMaquinasView = new CadastroMaquinasView();
        cadastroMaquinasView.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuMaquinasCadastroActionPerformed

    private void SubMenuLaboratorioMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuLaboratorioMaquinasActionPerformed
        CadastroMaquinasView cadastroMaquinasView = new CadastroMaquinasView();
        cadastroMaquinasView.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuLaboratorioMaquinasActionPerformed

    private void SubMenuLaboratorioPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuLaboratorioPecasActionPerformed
        CadastroPecaView cadastroPecaView = new CadastroPecaView();
        cadastroPecaView.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuLaboratorioPecasActionPerformed

    private void SubMenuPecasCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuPecasCadastroActionPerformed
        CadastroPecaView cadastroPecaView = new CadastroPecaView();
        cadastroPecaView.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuPecasCadastroActionPerformed

    private void SubMenuPecasManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuPecasManutencaoActionPerformed
        AssociarPecaManutencaoView pecaManutencao = new AssociarPecaManutencaoView();
        pecaManutencao.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuPecasManutencaoActionPerformed

    private void SubMenuRelatorioMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuRelatorioMaquinasActionPerformed
        RelatoriosView relatorioMaquinas = new RelatoriosView();
        relatorioMaquinas.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuRelatorioMaquinasActionPerformed

    private void SubMenuRelatorioPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuRelatorioPecasActionPerformed
        RelatoriosView relatorioPeca = new RelatoriosView();
        relatorioPeca.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuRelatorioPecasActionPerformed

    private void SubMenuRelatorioLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuRelatorioLaboratorioActionPerformed
        RelatoriosView relatorioLabin = new RelatoriosView();
        relatorioLabin.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuRelatorioLaboratorioActionPerformed

    private void SubMenuManutencaoPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuManutencaoPecasActionPerformed
        AssociarPecaManutencaoView pecaManutencao = new AssociarPecaManutencaoView();
        pecaManutencao.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuManutencaoPecasActionPerformed

    private void SubMenuManutencaoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuManutencaoMaquinasActionPerformed
        ManutencaoMaquinaView manutencaoMaquina = new ManutencaoMaquinaView();
        manutencaoMaquina.setVisible(true);
        dispose();// fecha a tela que está.
    }//GEN-LAST:event_SubMenuManutencaoMaquinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLaboratorio;
    private javax.swing.JMenu MenuManutencao;
    private javax.swing.JMenu MenuMaquinas;
    private javax.swing.JMenu MenuPecas;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenuItem SubMenuLaboratorioMaquinas;
    private javax.swing.JMenuItem SubMenuLaboratorioPecas;
    private javax.swing.JMenuItem SubMenuManutencaoMaquinas;
    private javax.swing.JMenuItem SubMenuManutencaoPecas;
    private javax.swing.JMenuItem SubMenuMaquinasCadastro;
    private javax.swing.JMenuItem SubMenuMaquinasManutencao;
    private javax.swing.JMenuItem SubMenuPecasCadastro;
    private javax.swing.JMenuItem SubMenuPecasManutencao;
    private javax.swing.JMenuItem SubMenuRelatorioLaboratorio;
    private javax.swing.JMenuItem SubMenuRelatorioMaquinas;
    private javax.swing.JMenuItem SubMenuRelatorioPecas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
