/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.awt.EventQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class UsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioView
     */
    public UsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNovoUsuario = new javax.swing.JTextField();
        txtNovaSenhaUsuario = new javax.swing.JPasswordField();
        TipoDePerfil = new javax.swing.JComboBox<>();
        btnCadastrarNVUsuario = new javax.swing.JButton();
        btnVoltaATelaLogin = new javax.swing.JButton();
        txtEmailNVUsuario = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();

        setResizable(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Criar conta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("Nome de Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setText("Senha");

        txtNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoUsuarioActionPerformed(evt);
            }
        });

        txtNovaSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaSenhaUsuarioActionPerformed(evt);
            }
        });

        TipoDePerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE PERFIL", "ADMIN", "TECNICO", "PROFFESSOR", "ESTÁGIARIO" }));
        TipoDePerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDePerfilActionPerformed(evt);
            }
        });

        btnCadastrarNVUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/adicionar-usuario.png"))); // NOI18N
        btnCadastrarNVUsuario.setText("Cadastrar");
        btnCadastrarNVUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarNVUsuarioActionPerformed(evt);
            }
        });

        btnVoltaATelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/voltar.png"))); // NOI18N
        btnVoltaATelaLogin.setText("Ir a Tela de Login");
        btnVoltaATelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaATelaLoginActionPerformed(evt);
            }
        });

        txtEmailNVUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailNVUsuarioActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lblEmail.setText("EMAIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TipoDePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmailNVUsuario))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNovoUsuario)
                .addContainerGap())
            .addComponent(txtNovaSenhaUsuario)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnCadastrarNVUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltaATelaLogin)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TipoDePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailNVUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovaSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarNVUsuario)
                    .addComponent(btnVoltaATelaLogin))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDePerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDePerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDePerfilActionPerformed

    private void txtNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovoUsuarioActionPerformed

    private void txtNovaSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSenhaUsuarioActionPerformed

    private void btnCadastrarNVUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarNVUsuarioActionPerformed
       String nomeUsuario = txtNovoUsuario.getText();
    String senha = new String(txtNovaSenhaUsuario.getPassword());
    String email = txtEmailNVUsuario.getText(); 
    String perfil = (String) TipoDePerfil.getSelectedItem();

    // Verifica se o e-mail é válido
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(this, "Por favor, insira um e-mail válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verifica se todos os campos foram preenchidos e o perfil selecionado é válido
    if (nomeUsuario.isEmpty() || senha.isEmpty() || email.isEmpty() || perfil.equals("TIPO DE PERFIL")) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos e selecione um perfil válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    UsuarioDTO usuarioDTO = new UsuarioDTO();
    usuarioDTO.setNomeUsuario(nomeUsuario);
    usuarioDTO.setSenha(senha);
    usuarioDTO.setEmail(email);
    usuarioDTO.setPerfil(perfil);

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    boolean sucesso = usuarioDAO.cadastrarUsuario(usuarioDTO);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

        // Abre a tela de Login após o cadastro
        EventQueue.invokeLater(() -> {
            LoginView loginView = new LoginView();
            loginView.setVisible(true);
        });
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCadastrarNVUsuarioActionPerformed

    private void btnVoltaATelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaATelaLoginActionPerformed
        // Fecha a tela atual e abre a tela de login
         this.dispose();
        EventQueue.invokeLater(() -> {
            LoginView loginView = new LoginView();
            loginView.setVisible(true);
        });
    }//GEN-LAST:event_btnVoltaATelaLoginActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void txtEmailNVUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailNVUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailNVUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TipoDePerfil;
    private javax.swing.JButton btnCadastrarNVUsuario;
    private javax.swing.JButton btnVoltaATelaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JTextField txtEmailNVUsuario;
    private javax.swing.JPasswordField txtNovaSenhaUsuario;
    private javax.swing.JTextField txtNovoUsuario;
    // End of variables declaration//GEN-END:variables
}
