/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Joel
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMaquinas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuPecas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        MenuConserto = new javax.swing.JMenu();
        MenuEstoque = new javax.swing.JMenu();
        MenuHistorico = new javax.swing.JMenu();
        MenuLaboratorio = new javax.swing.JMenu();
        MenuUsu = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuMaquinas.setText("Maquinas");
        MenuMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMaquinasActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Marca");
        MenuMaquinas.add(jMenuItem1);

        jMenuItem2.setText("Modelo");
        MenuMaquinas.add(jMenuItem2);

        jMenuBar1.add(MenuMaquinas);

        MenuPecas.setText("Peças");
        MenuPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPecasActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Mouse");
        MenuPecas.add(jMenuItem3);

        jMenuItem4.setText("Teclados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuPecas.add(jMenuItem4);

        jMenuItem5.setText("Monitor");
        MenuPecas.add(jMenuItem5);

        jMenuItem6.setText("Fonte");
        MenuPecas.add(jMenuItem6);

        jMenuItem7.setText("Cabos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MenuPecas.add(jMenuItem7);

        jMenuBar1.add(MenuPecas);

        MenuRelatorio.setText("Relatório");
        MenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenuItem8);

        jMenuBar1.add(MenuRelatorio);

        MenuConserto.setText("Conserto");
        MenuConserto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsertoActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuConserto);

        MenuEstoque.setText("Estoque");
        MenuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEstoqueActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuEstoque);

        MenuHistorico.setText("Historico");
        MenuHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHistoricoActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuHistorico);

        MenuLaboratorio.setText("Laboratório");
        MenuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaboratorioActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuLaboratorio);

        MenuUsu.setText("Usuario");
        MenuUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuUsu);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MenuMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMaquinasActionPerformed

    private void MenuPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPecasActionPerformed

    private void MenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatorioActionPerformed

    private void MenuConsertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsertoActionPerformed

    private void MenuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEstoqueActionPerformed

    private void MenuHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHistoricoActionPerformed

    private void MenuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLaboratorioActionPerformed

    private void MenuUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUsuActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConserto;
    private javax.swing.JMenu MenuEstoque;
    private javax.swing.JMenu MenuHistorico;
    private javax.swing.JMenu MenuLaboratorio;
    private javax.swing.JMenu MenuMaquinas;
    private javax.swing.JMenu MenuPecas;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuUsu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
